create table public.roadbook_start_point_history (
  id bigint generated by default as identity primary key,
  roadbook_id bigint not null references public.roadbooks(id) on delete cascade,
  operation text not null check (operation in ('UPDATE', 'DELETE')),
  before_snapshot jsonb not null,
  after_snapshot jsonb,
  changed_by uuid,
  changed_at timestamptz not null default now()
);

create index roadbook_start_point_history_roadbook_changed_idx
  on public.roadbook_start_point_history (roadbook_id, changed_at desc);

alter table public.roadbook_start_point_history enable row level security;

revoke all on table public.roadbook_start_point_history from anon, authenticated;
grant select on table public.roadbook_start_point_history to authenticated;

create policy roadbook_start_point_history_editor_read
on public.roadbook_start_point_history for select to authenticated
using (private.is_roadbook_editor(roadbook_id));

create or replace function private.journey_has_content(value jsonb)
returns boolean
language sql
immutable
security invoker
set search_path = ''
as $$
  select coalesce(nullif(btrim(value->>'description'), ''), '') <> ''
    or jsonb_array_length(coalesce(value->'transport_segments', '[]'::jsonb)) > 0
    or jsonb_array_length(coalesce(value->'route_maps', '[]'::jsonb)) > 0
    or jsonb_array_length(coalesce(value->'photos', '[]'::jsonb)) > 0
    or jsonb_array_length(coalesce(value->'accommodations', '[]'::jsonb)) > 0
    or jsonb_array_length(coalesce(value->'pois', '[]'::jsonb)) > 0;
$$;

revoke all on function private.journey_has_content(jsonb) from public, anon, authenticated;

create or replace function private.preserve_and_archive_roadbook_start_point()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
begin
  if tg_op = 'UPDATE' then
    if private.journey_has_content(old.return_trip)
       and not private.journey_has_content(new.return_trip) then
      new.return_trip := old.return_trip;
    end if;

    if (to_jsonb(old) - 'updated_at') is not distinct from (to_jsonb(new) - 'updated_at') then
      return new;
    end if;
  end if;

  insert into public.roadbook_start_point_history (roadbook_id, operation, before_snapshot, after_snapshot, changed_by)
  values (
    old.roadbook_id,
    tg_op,
    to_jsonb(old),
    case when tg_op = 'UPDATE' then to_jsonb(new) else null end,
    (select auth.uid())
  );

  return case when tg_op = 'DELETE' then old else new end;
end;
$$;

revoke all on function private.preserve_and_archive_roadbook_start_point() from public, anon, authenticated;

create trigger roadbook_start_points_preserve_and_archive
before update or delete on public.roadbook_start_points
for each row execute function private.preserve_and_archive_roadbook_start_point();
